services:
  - type: web
    name: fn-matchmaker
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
      - key: SECRET
        sync: false  # Set manually in Render Dashboard
